TOOLCHAIN = "clang"
DEBUG_BUILD = "0"

FULL_OPTIMIZATION:toolchain-clang = "-Oz -pipe"

PACKAGE_DEBUG_SPLIT_STYLE:toolchain-clang = "none"
INHIBIT_PACKAGE_DEBUG_SPLIT:toolchain-clang = "1"

LLVM_TARGETS_TO_BUILD="ARM;X86"

# Force using llvm libc++, but not when bootstraping or with gcc
TC_CXX_RUNTIME:class-target:toolchain-clang = "llvm"


# Fix mips kernel build
LINKER_HASH_STYLE:mipsarch = "sysv"
LLVM_TARGETS_TO_BUILD:append =";Mips"
# mips-oe-linux-ld.lld: error: relocation R_MIPS_32 cannot be used against local symbol; recompile with -fPIC
TC_CXX_RUNTIME:class-target:toolchain-clang:mipsarch = ""
LIBCPLUSPLUS:class-target:toolchain-clang:mipsarch = ""

# Fix riscv32 bootstrap
LLVM_TARGETS_TO_BUILD:append =";RISCV"
