inherit image-artifact-names

C2A_INITRAMFS_IMAGE ?= "c2a-initrd-image"
C2A_SYSTEM_IMAGE ?= "c2a-system-image"

C2A_WIC_KERNEL_NAME ?= "fitImage-${INITRAMFS_IMAGE_NAME}-${MACHINE}"
C2A_WIC_KERNEL_PATH ?= "${DEPLOY_DIR_IMAGE}/${C2A_WIC_KERNEL_NAME}"

C2A_WIC_KERNEL_IMAGE_NAME ?= "Image"
C2A_WIC_KERNEL_IMAGE_PATH ?= "${DEPLOY_DIR_IMAGE}/${C2A_WIC_KERNEL_IMAGE_NAME}"

C2A_WIC_KERNEL_UZIMAGE_NAME ?= "${KERNEL_IMAGETYPE}"
C2A_WIC_KERNEL_UZIMAGE_PATH ?= "${DEPLOY_DIR_IMAGE}/${C2A_WIC_KERNEL_UZIMAGE_NAME}"

C2A_WIC_INITRAMFS_EXT ?= "${@((d.getVar('C2A_INITRAMFS_FSTYPES') or d.getVar('INITRAMFS_FSTYPES') or '').split() or [''])[0]}"
C2A_WIC_INITRAMFS_NAME ?= "${C2A_INITRAMFS_IMAGE}-${MACHINE}.${C2A_WIC_INITRAMFS_EXT}"
C2A_WIC_INITRAMFS_PATH ?= "${DEPLOY_DIR_IMAGE}/${C2A_WIC_INITRAMFS_NAME}"

C2A_WIC_C2AFLASH_NAME ?= "${C2A_SYSTEM_IMAGE}-${MACHINE}.rootfs.c2aflash"
C2A_WIC_C2AFLASH_PATH ?= "${DEPLOY_DIR_IMAGE}/${C2A_WIC_C2AFLASH_NAME}"

C2A_WIC_UBOOT_PATH = "${DEPLOY_DIR_IMAGE}/${UBOOT_BINARY}" 

C2A_WIC_IMAGE_NAME = "${C2A_SYSTEM_IMAGE}-${MACHINE}.rootfs.wic"
C2A_WIC_IMAGE_PATH ?= "${DEPLOY_DIR_IMAGE}/${C2A_WIC_IMAGE_NAME}"

C2A_BUNDLE_ARTIFACTS ?= "\
    ${C2A_WIC_C2AFLASH_PATH},${MACHINE}.c2aflash,${@'1' if (d.getVar('C2A_FLASH_PARTITIONS') or '').strip() else '0'} \
    ${C2A_WIC_IMAGE_PATH},${MACHINE}.wic,${@'1' if d.getVar('C2A_SUPPORTS_WIC') == '1' else '0'} \
    ${C2A_WIC_KERNEL_PATH},${MACHINE}.fitImage,${@'1' if d.getVar('KERNEL_IMAGETYPE') == 'fitImage' else '0'} \
    ${C2A_WIC_KERNEL_UZIMAGE_PATH},${MACHINE}.${KERNEL_IMAGETYPE},${@'1' if d.getVar('KERNEL_IMAGETYPE') in ('uzImage', 'uzImage.bin') else '0'} \
    ${C2A_WIC_KERNEL_UZIMAGE_PATH},${MACHINE}.${KERNEL_IMAGETYPE}.bin,${@'1' if d.getVar('KERNEL_IMAGETYPE') in ('Image', 'c2rvImage') else '0'} \
    ${C2A_WIC_KERNEL_IMAGE_PATH},${MACHINE}.Image.bin,${@'1' if d.getVar('KERNEL_IMAGETYPE') in ('c2rvImage') else '0'} \
    ${C2A_WIC_INITRAMFS_PATH},${MACHINE}.initrd.bin,1 \
"
