require conf/machine/include/clk-mini-ultra/shared.conf
require conf/machine/include/clk-mini-ultra/flash-nor.conf
require conf/machine/include/clk-mini-ultra/recovery.conf

require conf/system/include/c2a/machine-boot/erofs-base.conf
#require conf/system/include/c2a/machine-boot/initramfs.conf

# catplay-bench
MACHINE_FIRMWARE:append = " i2c-tools devmem2 catplay-g-iphone"
C2A_FLASH_PARTITIONS = ""
C2A_BUNDLE_NAME = "clk-mini-ultra-nor"
C2A_BUNDLE_EXTRA_DEPENDS:append = " carlinkit-mini-flasher:do_deploy"

C2A_BUNDLE_ARTIFACTS:append = " ${DEPLOY_DIR_IMAGE}/ax1800_spi_nor_burner_u-boot-spl.bin,ax1800_spi_nor_burner_u-boot-spl.bin,1"
C2A_BUNDLE_ARTIFACTS:append = " \
 ${DEPLOY_DIR_IMAGE}/tools/errors.py,tools/errors.py,1 \
 ${DEPLOY_DIR_IMAGE}/tools/exploit.py,tools/exploit.py,1 \
 ${DEPLOY_DIR_IMAGE}/tools/flash.py,tools/flash.py,1 \
 ${DEPLOY_DIR_IMAGE}/tools/reboot2recovery.py,tools/reboot2recovery.py,1 \
 ${DEPLOY_DIR_IMAGE}/tools/recov.py,tools/recov.py,1 \
 ${DEPLOY_DIR_IMAGE}/tools/trampoline.py,tools/trampoline.py,1 \
 ${DEPLOY_DIR_IMAGE}/tools/uimage.py,tools/uimage.py,1 \
 ${DEPLOY_DIR_IMAGE}/tools/uploader.py,tools/uploader.py,1 \
"
