# Preferred bundle type for riscv32. See kernel-riscv-bundle-c2a.bbclass
require conf/system/include/c2a/machine-boot/erofs-base.conf

C2A_APPEND = "root=/dev/initrd rootfstype=erofs rw quiet"

KERNEL_CLASSES = "kernel-riscv-bundle-c2a"
KERNEL_IMAGETYPES = "c2rvImage Image"
KERNEL_IMAGETYPE = "c2rvImage"
