# Flash layout
# Needs to be in sync with: .dts AND letux-uboot patches
C2A_FLASH_SIZE = "16M" 

FLASH_UBOOT_BIN = "${DEPLOY_DIR_IMAGE}/ax1800_spi_nor_u-boot-spl.bin"
FLASH_KERNEL_BIN = "${DEPLOY_DIR_IMAGE}/${KERNEL_IMAGETYPE}"
FLASH_INITRD_BIN = "${DEPLOY_DIR_IMAGE}/${C2A_INITRAMFS_IMAGE}-${MACHINE}.erofs-lz4hc"
FLASH_PERSIST_BIN = "${IMGDEPLOYDIR}/${IMAGE_LINK_NAME}.${C2A_ROOTFS_FSTYPE}"

C2A_FLASH_PARTITIONS = "\
    ${FLASH_UBOOT_BIN} 0x00000000 0x00020000 \
    ${FLASH_KERNEL_BIN} 0x00020000 0x00380000 \
    ${FLASH_INITRD_BIN} 0x003a0000 0x00b80000 \
    ${FLASH_PERSIST_BIN} 0x00f20000 0x000E0000 \
"
